site_name: Base FastAPI
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Base FastAPI: index.md
  - Setup Oauth2 Provider:
      - oauth2_providers/google.md
      - oauth2_providers/facebook.md
